// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8R6Y9XBKjzzile0NhgUX9a_HJ0TCZhdw',
    appId: '1:867584262781:web:949c7fbbab7c58c454e714',
    messagingSenderId: '867584262781',
    projectId: 'learn-english-27ea5',
    authDomain: 'learn-english-27ea5.firebaseapp.com',
    storageBucket: 'learn-english-27ea5.firebasestorage.app',
    measurementId: 'G-0TV9RP1LDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtCaXmriJjhemu6ONI5KtRZZRdl0XTuOs',
    appId: '1:867584262781:android:909913650f38cde054e714',
    messagingSenderId: '867584262781',
    projectId: 'learn-english-27ea5',
    storageBucket: 'learn-english-27ea5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-xsZSo3NXWXt_SAWd2l3CSrrZy3wVjrU',
    appId: '1:867584262781:ios:48487112841bd7d354e714',
    messagingSenderId: '867584262781',
    projectId: 'learn-english-27ea5',
    storageBucket: 'learn-english-27ea5.firebasestorage.app',
    iosBundleId: 'com.example.learnEnglish',
  );
}
